config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :bills
  resources :employees
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :employee
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :employees
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department
  has_many :bills, dependent: :destroy
  
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: %i[ show edit update destroy ]
  before_action :get_employees

  # GET /bills or /bills.json
  def index
    @bills = Bill.all
    @total_amount = @bills.sum(:amount)
  end

  # GET /bills/1 or /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills or /bills.json
  def create
    @bill = Bill.new(bill_params)
    respond_to do |format|
      if @bill.save
        format.html { redirect_to bills_url, notice: "Bill was successfully created." }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1 or /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to bills_url, notice: "Bill was successfully updated." }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1 or /bills/1.json
  def destroy
    @bill.destroy!

    respond_to do |format|
      format.html { redirect_to bills_url, notice: "Bill was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    def get_employees
      @employees = Employee.all
    end

    # Only allow a list of trusted parameters through.
    def bill_params
      params.require(:bill).permit(:amount, :bill_type, :employee_id)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]
  before_action :get_departments

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employees_url, notice: "Employee was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employees_url, notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy!

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def get_departments
      @departments = Department.all
    end
    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :email, :designation, :department_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller_stylesheet_link_tag
    stylesheet_link_tag params[:controller]
  end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bills/_bill.html.erb
<tr id="<%= dom_id bill %>">

  <td>
    <%= bill.bill_type %>
  </td>

  <td>
    <%= bill.amount %>
  </td>

  <td>
    <%= bill.created_at.strftime("%d-%m-%Y") %>
  </td>

  <td>
    <%= bill.employee.full_name %>
  </td>

  <td>
    <%= bill.employee.department.name %>
  </td>

  <td>
    <%= link_to edit_bill_path(bill), class:"btn btn-warning" do %>
      <i class="fas fa-edit"></i>
    <% end %>
  </td>

  <td>
    <%= button_to bill, method: :delete, class:"btn btn-warning" do %>
      <i class="fas fa-trash-alt"></i>
    <% end %>
  </td>

</div>

app/views/bills/_form.html.erb
<section class="intro">
  <div class="gradient-custom-1 h-100">
    <div class="d-flex pt-5 mt-5 h-100">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-6">
            <div class="card shadow-lg border-0 rounded">
              <div class="card-body">
                <h2 class="card-title text-center"><%= @bill.new_record? ? 'New Bill' : 'Edit Bill' %></h2>
                <%= form_with(model: bill, local: true) do |form| %>
                  
                  <div class="mb-3">
                    <%= form.label :amount, class: 'form-label' %>
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <span class="input-group-text">INR</span>
                      </div>
                      <%= form.text_field :amount, class: 'form-control' %>
                    </div>
                  </div>

                  
                  <div class="mb-3">
                    <%= form.label :type, class: 'form-label' %>
                    <%= form.collection_select :bill_type, TYPES.map { |type| [type, type] }, :last, :first, { prompt: "Select Type" }, { class: 'form-select' } %>
                  </div>

                  
                  <div class="mb-3">
                    <%= form.label :employee_id, class: 'form-label'%>
                    <%= form.collection_select :employee_id, @employees, :id, :full_name, { prompt:"Select employee" }, { class: 'form-select'} %>
                  </div>

                  <div class="row mt-4">
                    <div class="col-6">
                      <%= link_to 'Back', bills_path, class: "btn btn-secondary" %>
                    </div>
                    <div class="col-6 text-end">
                      <%= form.submit 'Save', class: "btn btn-success" %>
                    </div>
                  </div>

                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/bills/edit.html.erb
<%= render "form", bill: @bill %>

app/views/bills/index.html.erb
<section class="intro">
  <div class="gradient-custom-1 h-100">
    <div class="d-flex h-100 mt-5 pt-5">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-12">
            <div class="card shadow-lg border-0 rounded">
              <div class="card-body">
                <div class="row">
                  <div class="col-6">
                    <h2 class="card-title" style="color: #8645b5">Bills</h2>
                  </div>
                  
                  <div class="col-6 text-end mt-2">
                    <%= link_to new_bill_path, class: "btn", style:"color:white; background-color:#7e38b0" do %>
                      <i class="fas fa-plus"></i>
                      Create Bill
                    <% end %>
                  </div>
                </div>
                <% if @bills.any?%>
                  <div class="row mt-4">
                    <div class="col-md-12">
                      <p class="h4 font-weight-bold">Total Submitted Amount <%= number_to_currency(@total_amount, unit: "₹") %></span></p>
                    </div>
                  </div>
                <% end %>
                  <div class="table-responsive mt-5">
                    <table class="table table-hover mb-3" id="employees">
                      <thead class="thead-dark">
                        <tr>
                          <th scope="col">TYPE</th>
                          <th scope="col">AMOUNT</th>
                          <th scope="col">DATE OF SUBMISSION</th>
                          <th scope="col">SUBMITTED BY</th>
                          <th scope="col">DEPARTMENT</th>
                          <th></th>
                          <th></th>
                        </tr>
                      </thead>
                      <tbody class="mt-4">
                        <% @bills.each do |bill| %>
                          <%= render bill %>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                <div class="row mt-4">
                  <div class="text-center">
                    <%= link_to 'Back', employees_path, class: "btn btn-secondary" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/bills/new.html.erb
<%= render "form", bill: @bill %>

app/views/employees/_employee.html.erb
<tr id="<%= dom_id employee %>" class="employee">
  <td>
    <%= employee.full_name %>
  </td>

  <td>
    <%= employee.designation %>
  </td>

  <td>
    <%= employee.department.name %>
  </td>

  <td>
    <%= link_to edit_employee_path(employee), class:"btn btn-warning" do %>
      <i class="fas fa-edit"></i>
    <% end %>
  </td>

  <td>
    <%= button_to employee, method: :delete, class:"btn btn-warning" do %>
      <i class="fas fa-trash-alt"></i>
    <% end %>
  </td>
  
</tr>

app/views/employees/_form.html.erb
<section class="intro">
  <div class="gradient-custom-1 h-100">
    <div class="d-flex pt-5 mt-5 h-100">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-6">
            <div class="card shadow-lg border-0 rounded">
              <div class="card-body">
                <h2 class="card-title text-center"><%= @employee.new_record? ? 'New Employee' : 'Edit Employee' %></h2>
                <%= form_with(model: employee, class: 'needs-validation', novalidate: true) do |form| %>
                  
                  <div class="row">
                    <div class="col-6">
                      <%= form.label :first_name, class: 'form-label' %>
                      <%= form.text_field :first_name, class: 'form-control', required: true %>
                    </div>

                    <div class="col-6">
                      <%= form.label :last_name, class: 'form-label' %>
                      <%= form.text_field :last_name, class: 'form-control', required: true %>
                    </div>
                  </div>

                  <div class="mb-3">
                    <%= form.label :email, class: 'form-label' %>
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <span class="input-group-text">@</span>
                      </div>
                      <%= form.text_field :email, class: 'form-control', required: true  %>
                    </div>
                  </div>

                  <div class="mb-3">
                    <%= form.label :designation, class: 'form-label' %>
                    <%= form.text_field :designation, class: 'form-control', required: true %>
                  </div>

                  <div class="mb-3">
                    <%= form.label :department_id, class: 'form-label' %>
                    <%= form.collection_select :department_id, @departments, :id, :name, { prompt: "Select a Department" }, { class: 'form-select' } %>
                  </div>

                  <div class="row mt-4">
                    <div class="col-6">
                      <%= link_to 'Back', employees_path, class: "btn btn-secondary" %>
                    </div>

                    <div class="col-6 text-end">
                      <%= form.submit 'Save', class: "btn btn-success" %>
                    </div>
                  </div>

                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/employees/edit.html.erb
<%= render "form", employee: @employee %>

app/views/employees/index.html.erb
<section class="intro">
  <div class="gradient-custom-1 h-100">
    <div class="d-flex h-100 mt-5">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-12">
            <div class="card shadow-lg border-0 rounded">
              <div class="card-body">
                <h2 class="card-title text-center">Employee List</h2>
                <div class="table-responsive mt-5">
                  <% if @employees.any? %>
                    <table class="table table-hover mb-0" id="employees">
                      <thead class="thead-dark">
                        <tr>
                          <th scope="col">FULL NAME</th>
                          <th scope="col">DESIGNATION</th>
                          <th scope="col">DEPARTMENT</th>
                          <th></th>
                          <th></th>
                        </tr>
                      </thead>
                      <tbody class="mt-4">
                        <% @employees.each do |employee| %>
                          <%= render employee %>
                        <% end %>
                      </tbody>
                    </table>
                  <% else %>
                  <p class="no-employees-message"><i class="fas fa-exclamation-triangle"></i>No employees found. Create employees to get started</p>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/employees/new.html.erb
<%= render "form", employee: @employee %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReimbursementPortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'cashback.png' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light navbar-custom">
      <a class="navbar-brand" href="#">
        <%= image_tag 'cashback.png', alt: 'Reimbursement Portal Logo' %>
        <span class="portal"> Reimbursement Portal</span>
      </a>
      <% if controller_name != 'welcome' %>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item mr-3">
              <%= link_to 'View Bills', bills_path, class: 'nav-link fw-bold', id: 'new_bill' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Add Employee', new_employee_path, class: 'nav-link fw-bold' %>
            </li>
          </ul>
        </div>
      <% end %>
    </nav>

    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>   
  </body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome | Reimbursement Portal</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_importmap_tags %>
</head>
<body>
  <div class="welcome-background"></div>
    <div class="welcome-content container-fluid d-flex flex-column justify-content-center align-items-center vh-100">
      <h1>Welcome to Reimbursement Portal</h1>
      <a href="<%= employees_path %>" class="btn btn-light btn-lg mt-4">Get Started <i class="fas fa-arrow-right"></i></a>
    </div>
  </div>
</body>
</html>